# Generated by Django 5.1.1 on 2024-09-10 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_booking_id_alter_booking_no_of_guests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_id',
        ),
    ]
