# Generated by Django 5.1.1 on 2024-09-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_booking_booking_id_remove_menu_menu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='inventory',
            field=models.IntegerField(default=1),
        ),
    ]
